# Data Preprocessing

In [1]:
import pandas as pd

In [2]:
edges = pd.read_csv('UofT_edges.csv')

In [3]:
edges

          source    target          emt
0       983859.0  544485.0   503.807815
1       605618.0  362627.0  5157.568486
2       323189.0  118238.0   498.628481
3       919153.0  983859.0   401.962668
4       995748.0  983859.0  5095.458776
...          ...       ...          ...
466228  743092.0  307628.0  2959.506391
466229  420266.0  489593.0   208.011081
466230  441447.0  877470.0  2221.199295
466231  444883.0  137297.0  1175.932049
466232  500103.0  123640.0   100.431608

[466233 rows x 3 columns]

In [4]:
nodes = pd.read_csv('UofT_nodes.csv')

In [5]:
nodes

,BIRTH_DT,CUST_ADD_DT,OCPTN_NM,RES_CNTRY_CA,CNTRY_OF_INCOME_CA,PEP_FL,CASH_SUM_IN,CASH_CNT_IN,CASH_SUM_OUT,CASH_CNT_OUT,WIRES_SUM_IN,WIRES_CNT_IN,WIRES_SUM_OUT,WIRES_CNT_OUT,COUNTRY_RISK_INCOME,COUNTRY_RISK_RESIDENCY,RISK,NAME,GENDER,CUSTOMER_ID
0,1981-09-01,2007-07-05,89.0,1,1,0.0,2577.785,2.0,2851.663,7.0,70774.0,62.0,24244.0,35.0,Low,Low,low,"Young, Marie Mildren Coleman",Female,935382.0
1,1994-02-21,2019-05-19,89.0,1,1,0.0,3035.502,2.0,4805.997,15.0,282929.0,76.0,196439.0,152.0,Low,Low,low,Mark Stupar Lecy,Male,2305.0
2,1962-11-16,2011-08-02,89.0,1,1,0.0,1617.571,1.0,3482.809,11.0,7632.0,6.0,33598.0,20.0,Low,Low,low,Dean Glasper Wendel Reeves,Male,472403.0
3,1998-06-20,2001-08-15,89.0,1,1,0.0,3587.042,5.0,1940.943,8.0,149253.0,71.0,105896.0,238.0,Low,Low,low,"Hulsey, Linda Rauth",Female,227994.0
4,1942-01-24,2012-10-28,89.0,1,1,0.0,1725.524,2.0,13197.169,43.0,92318.0,96.0,187403.0,180.0,Low,Low,low,Carolyn Washington Roberts,Female,418265.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1939-01-16,1994-03-19,467.0,0,1,0.0,18945.108,10.0,32210.000,21.0,1186467.0,25.0,2550098.0,174.0,Low,High,high,Bret* Dove Gainey,Male,420884.0
999996,1970-12-13,1995-12-22,467.0,0,1,0.0,5775.601,7.0,5015.741,15.0,244504.0,53.0,417992.0,337.0,Low,Low,low,Anthony Ray Montano Gomez,Male,429418.0
999997,1958-09-09,2010-11-03,65.0,0,1,0.0,2351.255,2.0,15997.000,19.0,3024271.0,68.0,948981.0,124.0,Low,High,high,Bernadette Schofield Pace Mile,Female,731360.0
999998,1983-09-15,2013-01-30,231.0,0,1,0.0,27312.613,8.0,3399.000,5.0,943477.0,9.0,376429.0,12.0,Low,High,high,"Wasson, Russell Terrell",Male,837988.0
999999,1962-01-23,2017-03-07,89.0,0,0,0.0,1421.363,1.0,1276.000,1.0,683797.0,5.0,617628.0,12.0,High,High,high,Daniel Mckeighan,Male,166357.0

In [8]:
occupation = pd.read_csv('UofT_occupation_risk.csv')

In [9]:
occupation

     code occupation_risk
0       0             Low
1       1            High
2       2             Low
3       3             Low
4       4             Low
..    ...             ...
836   836             Low
837   837             Low
838   838             Low
839   839            High
840   840            High

[841 rows x 2 columns]

In [15]:
BadActorList = pd.read_csv('targets.simple.csv')

In [16]:
BadActorList

,id,schema,name,aliases,birth_date,countries,addresses,identifiers,sanctions,phones,emails,dataset,first_seen,last_seen
0,acf-00040861bc3f593000830d987d09967ef3503ef1,Person,Kolyvanov Egor,Колыванов Егор,1980-11-15,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
1,acf-0011c68a768924609dc5da5707ac7fa4c4d645a2,Person,Shipov Sergei Yurievich,Шипов Сергей Юрьевич,1966-04-17,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
2,acf-001e7e4c0363f08f1e784c230457960b84a6416f,Person,Egorov Ivan Mikhailovich,Егоров Иван Михайлович,1961-01-21,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
3,acf-002c208139012c8d93b6298358188d7cadafe648,Person,Goreslavsky Alexey Sergeyevich,Гореславский Алексей Сергеевич,1977-07-13,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-09-20 1:05,2023-01-08 12:16
4,acf-002cc8fdf8fe41185091a7cb6c598663e7a22eb5,Person,Samoilova Natalya Vladimirovna,Самойлова Наталья Владимировна,1987-06-24,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-09-20 1:05,2023-01-08 12:16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258656,wbdeb-716880,LegalEntity,MARCELO DANIEL ROMERO,NaN,NaN,ar,"NIEVA DE CASTILLA 214, ANDALGALÁ,4740, PROVINC...",NaN,Cross Debarment: IDB - 2022-12-20 - 2029-11-17,NaN,NaN,WorldBank Debarred Providers,2022-12-20 18:18,2023-01-08 12:29
258657,wbdeb-716916,LegalEntity,GESAWORLD GROUP S.A.,NaN,NaN,es,NaN,NaN,Cross Debarment: IDB - 2022-12-20 - 2032-11-13,NaN,NaN,WorldBank Debarred Providers,2022-12-21 0:48,2023-01-08 12:29
258658,wbdeb-717314,LegalEntity,GESAWORLD USA LIMITED LIABILITY,NaN,NaN,us,MIAMI,NaN,Cross Debarment: IDB - 2022-12-20 - 2032-11-13,NaN,NaN,WorldBank Debarred Providers,2022-12-22 18:25,2023-01-08 12:29
258659,wbdeb-718111,LegalEntity,GITTO COSTRUZIONI GENERALI NIGERIA LIMITED,NaN,NaN,ng,"PLOT 737 MABUSHI DISTRICT, ABUJA, FCT",NaN,Cross Debarment: AfDB - 2022-12-28 - 2026-09-08,NaN,NaN,WorldBank Debarred Providers,2022-12-28 20:15,2023-01-08 12:29
258660,wbdeb-83317,LegalEntity,SEYDOU IDANI,NaN,NaN,bf,NaN,NaN,Consultant Guidelines 1.25(a)(i) - 2004-10-25 ...,NaN,NaN,WorldBank Debarred Providers,2021-07-26 11:55,2023-01-08 12:29

# Text Processing

In [6]:
from string import punctuation
import nltk

In [7]:
print(punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [8]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ruiho\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [9]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
print(stop_words)

{'if', "you're", 'you', 'other', 'such', 'i', 'can', 'this', 'then', 'why', 'wasn', 'shan', 'once', 'ours', "you'd", 'doing', 'll', 'o', 'weren', 'few', 'ain', 'didn', "mustn't", 'isn', 'y', 'himself', 'a', 'into', 'before', 'just', 'them', "should've", 'couldn', 'those', 'be', 'through', 'the', 'out', 'over', 'did', 'which', 'they', 'he', "didn't", 'she', 'we', "it's", 'd', 'between', 't', 'until', 'won', 'by', 'have', 'during', 'ourselves', 'theirs', 'hers', 'while', 'up', "mightn't", "don't", 'don', 'only', 've', 'hasn', "couldn't", 'no', 'to', 'each', 'who', 'been', 'under', 'his', 'what', 'myself', 'of', 's', 'your', 'there', 'when', "shan't", 'these', 'her', "aren't", 'yours', "you'll", 'same', 'about', 'should', 'after', 'that', 'and', 'has', 'needn', "hadn't", 'me', 'aren', "hasn't", 'as', 'it', 'own', 'being', 'am', 'doesn', "wouldn't", 'because', 'from', 'any', 'an', "shouldn't", 'its', 'so', 'my', 'nor', 'than', 'all', 'yourselves', 'herself', 'or', 'their', "you've", "isn't", "weren't", 'very', 'below', 'mightn', 'some', 'are', 'more', 'on', 'further', 'here', 'for', 'm', 'against', 'most', 'themselves', 'not', 'had', 'was', 'down', 'him', 'having', 'does', "needn't", "she's", 'now', 'were', 'wouldn', 'both', 'in', 'but', "haven't", 'whom', 'mustn', "won't", 'do', 'will', 'too', 'ma', 'how', 'shouldn', "wasn't", 'hadn', 'off', 'above', 'haven', "doesn't", 'itself', 'where', 'at', 'our', "that'll", 'yourself', 'is', 'with', 're', 'again'}

In [ ]:
def clean_text(text):
    if pd.notnull(text):
        tokens = text.split()
        table = str.maketrans("","", punctuation) #creates a one to one mapping of a character to its translation/replacement
        tokens = [word.translate(table) for word in tokens]
        tokens = [word for word in tokens if word.isalpha()]
        tokens = [word.lower() for word in tokens]
        #tokens = [word for word in tokens if not word in stop_words]
        tokens = [word for word in tokens if len(word) > 1]
        return ' '.join(tokens)
    else:
        return text

Nodes

In [10]:
nodes['NAME'] = nodes['NAME'].str.strip()

In [11]:
nodes.head()

,BIRTH_DT,CUST_ADD_DT,OCPTN_NM,RES_CNTRY_CA,CNTRY_OF_INCOME_CA,PEP_FL,CASH_SUM_IN,CASH_CNT_IN,CASH_SUM_OUT,CASH_CNT_OUT,WIRES_SUM_IN,WIRES_CNT_IN,WIRES_SUM_OUT,WIRES_CNT_OUT,COUNTRY_RISK_INCOME,COUNTRY_RISK_RESIDENCY,RISK,NAME,GENDER,CUSTOMER_ID
0,1981-09-01,2007-07-05,89.0,1,1,0.0,2577.785,2.0,2851.663,7.0,70774.0,62.0,24244.0,35.0,Low,Low,low,"Young, Marie Mildren Coleman",Female,935382.0
1,1994-02-21,2019-05-19,89.0,1,1,0.0,3035.502,2.0,4805.997,15.0,282929.0,76.0,196439.0,152.0,Low,Low,low,Mark Stupar Lecy,Male,2305.0
2,1962-11-16,2011-08-02,89.0,1,1,0.0,1617.571,1.0,3482.809,11.0,7632.0,6.0,33598.0,20.0,Low,Low,low,Dean Glasper Wendel Reeves,Male,472403.0
3,1998-06-20,2001-08-15,89.0,1,1,0.0,3587.042,5.0,1940.943,8.0,149253.0,71.0,105896.0,238.0,Low,Low,low,"Hulsey, Linda Rauth",Female,227994.0
4,1942-01-24,2012-10-28,89.0,1,1,0.0,1725.524,2.0,13197.169,43.0,92318.0,96.0,187403.0,180.0,Low,Low,low,Carolyn Washington Roberts,Female,418265.0

In [13]:
nodes['NAME'] = nodes['NAME'].apply(clean_text)

In [24]:
nodes.head(50)

,BIRTH_DT,CUST_ADD_DT,OCPTN_NM,RES_CNTRY_CA,CNTRY_OF_INCOME_CA,PEP_FL,CASH_SUM_IN,CASH_CNT_IN,CASH_SUM_OUT,CASH_CNT_OUT,WIRES_SUM_IN,WIRES_CNT_IN,WIRES_SUM_OUT,WIRES_CNT_OUT,COUNTRY_RISK_INCOME,COUNTRY_RISK_RESIDENCY,RISK,NAME,GENDER,CUSTOMER_ID
0,1981-09-01,2007-07-05,89.0,1,1,0.0,2577.785,2.0,2851.663,7.0,70774.0,62.0,24244.0,35.0,Low,Low,low,young marie mildren coleman,Female,935382.0
1,1994-02-21,2019-05-19,89.0,1,1,0.0,3035.502,2.0,4805.997,15.0,282929.0,76.0,196439.0,152.0,Low,Low,low,mark stupar lecy,Male,2305.0
2,1962-11-16,2011-08-02,89.0,1,1,0.0,1617.571,1.0,3482.809,11.0,7632.0,6.0,33598.0,20.0,Low,Low,low,dean glasper wendel reeves,Male,472403.0
3,1998-06-20,2001-08-15,89.0,1,1,0.0,3587.042,5.0,1940.943,8.0,149253.0,71.0,105896.0,238.0,Low,Low,low,hulsey linda rauth,Female,227994.0
4,1942-01-24,2012-10-28,89.0,1,1,0.0,1725.524,2.0,13197.169,43.0,92318.0,96.0,187403.0,180.0,Low,Low,low,carolyn washington roberts,Female,418265.0
5,1969-05-22,2011-10-03,89.0,1,1,0.0,4274.825,8.0,10454.469,25.0,456359.0,107.0,276603.0,164.0,Low,Low,low,mary gilmore,Female,2473.0
6,1951-03-31,2007-08-07,89.0,1,1,0.0,6535.232,8.0,7059.521,21.0,74927.0,17.0,139436.0,58.0,Low,Low,low,jacqueline thompson burke spann,Female,568597.0
7,1986-08-26,2012-11-26,89.0,1,1,0.0,316.046,0.0,3894.914,16.0,335104.0,93.0,205929.0,205.0,Low,Low,low,alderson james mccombs wilcox,Male,395257.0
8,2002-06-24,2012-11-28,89.0,1,1,0.0,4684.540,9.0,1851.315,9.0,348805.0,83.0,521669.0,257.0,Low,Low,low,morris maria bitto minnick,Female,590694.0
9,1968-01-13,1997-12-23,89.0,1,1,0.0,3657.827,6.0,13503.562,35.0,413181.0,108.0,451743.0,315.0,Low,Low,low,mcneil jennifer delargy park,Female,738891.0
10,1957-11-11,2020-06-24,89.0,1,1,0.0,3757.159,4.0,4619.531,18.0,105145.0,28.0,124813.0,131.0,Low,Low,low,page sharon peak buroker,Female,145477.0
11,2007-06-26,2010-10-14,89.0,1,1,0.0,3642.725,4.0,5987.414,24.0,517504.0,250.0,321851.0,293.0,Low,Low,low,suzie garcia lavelle,Female,165550.0
12,1968-10-11,2001-11-05,89.0,1,1,0.0,5641.305,7.0,6188.607,14.0,297832.0,113.0,170592.0,113.0,Low,Low,low,sanders ronald schwerdtfeger,Male,996829.0
13,1978-12-20,2020-08-13,89.0,1,1,0.0,504.539,1.0,4229.858,13.0,161725.0,145.0,51606.0,137.0,Low,Low,low,jeanette williams krishun,Female,830984.0
14,1981-03-05,2005-12-06,89.0,1,1,0.0,558.155,1.0,2695.473,5.0,173376.0,30.0,111515.0,51.0,Low,Low,low,phipps mary sanchez smith,Female,110299.0
15,1979-06-18,2011-05-19,89.0,1,1,0.0,874.279,1.0,8374.486,23.0,438019.0,210.0,159282.0,205.0,Low,Low,low,danny aso tindle,Male,519854.0
16,1977-03-27,2001-08-16,89.0,1,1,0.0,1345.095,3.0,283.154,1.0,5067.0,3.0,34686.0,26.0,Low,Low,low,randy hunter summer,Male,834569.0
17,1950-07-16,1992-01-01,89.0,1,1,0.0,7509.701,7.0,13810.468,32.0,612063.0,131.0,387739.0,185.0,Low,Low,low,michelle pederson carlson mcilhinney,Female,643895.0
18,1956-07-06,1993-12-09,89.0,1,1,0.0,8722.896,13.0,1529.205,9.0,48676.0,26.0,160509.0,115.0,Low,Low,low,opal mapp diamond miller,Female,986889.0
19,1989-10-21,1994-06-15,89.0,1,1,0.0,4789.235,6.0,26.293,1.0,10513.0,11.0,19976.0,12.0,Low,Low,low,reed victoria dreessen lamontagne,Female,488331.0
20,1984-08-20,2008-02-10,89.0,1,1,0.0,483.715,1.0,3850.245,9.0,70050.0,5.0,137085.0,61.0,Low,Low,low,jackson birdie calkins,Female,510287.0
21,1994-01-16,1997-02-01,89.0,1,1,0.0,1522.977,2.0,3050.445,18.0,278584.0,187.0,326070.0,275.0,Low,Low,low,klug denice,Female,909430.0
22,1951-10-10,2002-10-27,89.0,1,1,0.0,3357.965,4.0,13146.867,32.0,90604.0,60.0,430218.0,358.0,Low,Low,low,nelson jason niceswander,Male,770745.0
23,1990-05-16,2006-12-04,89.0,1,1,0.0,5483.300,7.0,3881.041,20.0,387738.0,168.0,192178.0,241.0,Low,Low,low,rowena jennings ervin,Female,557273.0
24,1945-02-21,1982-03-14,89.0,1,1,0.0,913.855,1.0,7763.411,13.0,277256.0,69.0,208464.0,136.0,Low,Low,low,patricia wallner werner mcclain,Female,863774.0
25,1945-09-30,1997-04-17,89.0,1,1,0.0,1349.612,2.0,1756.053,5.0,176972.0,21.0,168036.0,60.0,Low,Low,low,romero david,Male,962283.0
26,1955-09-15,1982-01-01,89.0,1,1,0.0,2001.427,3.0,3360.415,11.0,446692.0,126.0,279672.0,169.0,Low,Low,low,kinser rose hill taylor,Female,576744.0
27,2003-01-23,2013-03-17,89.0,1,1,0.0,3921.454,6.0,1066.963,7.0,197055.0,47.0,218816.0,219.0,Low,Low,low,cheryl phares simpson carranza,Female,494758.0
28,1952-07-13,2011-01-15,89.0,1,1,0.0,2737.134,2.0,2370.788,8.0,157351.0,10.0,124260.0,32.0,Low,Low,low,susan gordon,Female,866806.0
29,1969-08-09,2003-09-27,89.0,1,1,0.0,680.728,1.0,450.397,0.0,42903.0,3.0,54136.0,14.0,Low,Low,low,julie smith owen smith,Female,582501.0
30,1988-09-01,2014-08-31,89.0,1,1,0.0,2261.294,2.0,13709.034,32.0,64362.0,16.0,43484.0,29.0,Low,Low,low,wilson sally,Female,936892.0
31,1926-11-15,1993-06-16,89.0,1,1,0.0,4242.149,4.0,686.860,4.0,235089.0,32.0,179646.0,93.0,Low,Low,low,vasquez marian pacheco fawver,Female,482730.0
32,1958-11-15,1992-03-24,89.0,1,1,0.0,485.289,0.0,9564.268,28.0,242563.0,44.0,114568.0,36.0,Low,Low,low,irene stone king diaz,Female,274783.0
33,1977-09-27,1994-04-22,89.0,1,1,0.0,3197.165,2.0,3935.802,17.0,294194.0,119.0,291502.0,249.0,Low,Low,low,betty pener aen,Female,484957.0
34,1966-11-29,2010-07-19,89.0,1,1,0.0,1451.280,3.0,1832.239,7.0,118624.0,10.0,187073.0,103.0,Low,Low,low,wixston ashley manes,Female,357303.0
35,1984-05-12,2007-01-01,89.0,1,1,0.0,2682.915,2.0,8465.681,18.0,585422.0,281.0,353528.0,223.0,Low,Low,low,frances gould,Female,313785.0
36,1947-09-05,1988-08-13,89.0,1,1,0.0,2385.071,5.0,10282.452,28.0,105758.0,16.0,76849.0,45.0,Low,Low,low,jimmy mierzejewski perez,Male,841328.0
37,1966-03-07,2002-12-13,89.0,1,1,0.0,4810.024,6.0,8897.740,21.0,310354.0,118.0,177360.0,228.0,Low,Low,low,katherine white forsmark,Female,411994.0
38,1957-03-26,2004-09-15,89.0,1,1,0.0,555.934,1.0,2768.117,9.0,260109.0,62.0,301255.0,144.0,Low,Low,low,charles boucher barrera,Male,595533.0
39,1950-07-09,2010-05-02,89.0,1,1,0.0,2605.273,1.0,1970.239,6.0,148592.0,28.0,120114.0,14.0,Low,Low,low,schade brian williams,Male,185316.0
40,1966-09-09,1987-08-20,89.0,1,1,0.0,1153.345,2.0,4518.356,15.0,222104.0,109.0,256693.0,124.0,Low,Low,low,english joan glosson,Female,628751.0
41,1957-01-07,2000-03-07,89.0,1,1,0.0,4244.712,4.0,12261.667,36.0,290586.0,156.0,454894.0,379.0,Low,Low,low,joseph millett strawn culp,Male,228005.0
42,1958-08-21,2000-12-20,89.0,1,1,0.0,1507.024,4.0,10048.541,19.0,30449.0,34.0,36179.0,63.0,Low,Low,low,juan lund kim miller,Male,884722.0
43,1980-10-06,2004-11-20,89.0,1,1,0.0,3793.859,5.0,4656.855,19.0,73245.0,26.0,86887.0,48.0,Low,Low,low,robert smith mchugh,Male,687503.0
44,1966-11-26,2012-02-03,89.0,1,1,0.0,8366.331,9.0,14973.055,42.0,556462.0,229.0,281352.0,175.0,Low,Low,low,sharon long navarro,Female,460848.0
45,1995-07-28,2009-01-12,89.0,1,1,0.0,1765.916,2.0,2573.217,6.0,304173.0,82.0,326954.0,221.0,Low,Low,low,james warren whitehead,Male,951053.0
46,1979-10-04,2017-06-10,89.0,1,1,0.0,1086.721,2.0,10448.007,27.0,185636.0,208.0,124637.0,120.0,Low,Low,low,hopper corey roberts wallen,Male,353867.0
47,2009-01-09,2016-01-18,89.0,1,1,0.0,955.570,1.0,3325.560,10.0,67373.0,31.0,83237.0,72.0,Low,Low,low,miller mary,Female,485871.0
48,1992-11-28,2020-04-20,89.0,1,1,0.0,9049.206,13.0,21082.430,52.0,154398.0,24.0,200071.0,119.0,Low,Low,low,hancock cindy hairston elliston,Female,155065.0
49,1967-03-04,1998-11-09,89.0,1,1,0.0,1574.855,4.0,6481.816,18.0,188537.0,68.0,363460.0,375.0,Low,Low,low,iris johns joe bischoff,Female,711745.0

Targets.Simple

In [17]:
BadActorList['name'] = BadActorList['name'].str.strip()

In [18]:
BadActorList.head()

,id,schema,name,aliases,birth_date,countries,addresses,identifiers,sanctions,phones,emails,dataset,first_seen,last_seen
0,acf-00040861bc3f593000830d987d09967ef3503ef1,Person,Kolyvanov Egor,Колыванов Егор,1980-11-15,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
1,acf-0011c68a768924609dc5da5707ac7fa4c4d645a2,Person,Shipov Sergei Yurievich,Шипов Сергей Юрьевич,1966-04-17,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
2,acf-001e7e4c0363f08f1e784c230457960b84a6416f,Person,Egorov Ivan Mikhailovich,Егоров Иван Михайлович,1961-01-21,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
3,acf-002c208139012c8d93b6298358188d7cadafe648,Person,Goreslavsky Alexey Sergeyevich,Гореславский Алексей Сергеевич,1977-07-13,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-09-20 1:05,2023-01-08 12:16
4,acf-002cc8fdf8fe41185091a7cb6c598663e7a22eb5,Person,Samoilova Natalya Vladimirovna,Самойлова Наталья Владимировна,1987-06-24,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-09-20 1:05,2023-01-08 12:16

In [19]:
BadActorList['name'] = BadActorList['name'].apply(clean_text)

In [23]:
BadActorList.head(50)

,id,schema,name,aliases,birth_date,countries,addresses,identifiers,sanctions,phones,emails,dataset,first_seen,last_seen
0,acf-00040861bc3f593000830d987d09967ef3503ef1,Person,kolyvanov egor,Колыванов Егор,1980-11-15,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
1,acf-0011c68a768924609dc5da5707ac7fa4c4d645a2,Person,shipov sergei yurievich,Шипов Сергей Юрьевич,1966-04-17,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
2,acf-001e7e4c0363f08f1e784c230457960b84a6416f,Person,egorov ivan mikhailovich,Егоров Иван Михайлович,1961-01-21,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
3,acf-002c208139012c8d93b6298358188d7cadafe648,Person,goreslavsky alexey sergeyevich,Гореславский Алексей Сергеевич,1977-07-13,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-09-20 1:05,2023-01-08 12:16
4,acf-002cc8fdf8fe41185091a7cb6c598663e7a22eb5,Person,samoilova natalya vladimirovna,Самойлова Наталья Владимировна,1987-06-24,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-09-20 1:05,2023-01-08 12:16
5,acf-003bf88296087aabb54ccd6db2bcd6928bc893b7,Person,tyutyunnik yury alexandrovich,Тютюнник Юрий Александрович,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
6,acf-004166f2e999e45c8ce9f497752a93f24f377198,Person,vlasova tatyana alekseevna,Власова Татьяна Алексеевна,1959-07-01,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-29 12:21,2023-01-08 12:16
7,acf-004ed1533d17996ba7aa11566f6c56027e2be689,Person,berzegova aseta muratovna,Берзегова Асета Муратовна,1988-08-23,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
8,acf-0062435b173149aba42212a1b16fb393d4a9bd0d,Person,shapovalov dmitry,Шаповалов Дмитрий,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
9,acf-00641aab3995732925809e5cc203623725c7219f,Person,kuular timur borisovich,Куулар Тимур Борисович,1971-08-20,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
10,acf-0069529d969231bfc2289d9f2d61db89de9bcc82,Person,homutova vita mikhailovna,Хомутова Вита Михайловна,1969-01-26,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
11,acf-00749769d332749ea1839ce82ddad4f18b3187d2,Person,gimaltdinov firdus salikhovich,Гималтдинов Фирдус Салихович,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
12,acf-00776ee02694fb36ef3d6f42fa95ddcdab7f76c8,Person,vasilev vladimir lvovich,Васильев Владимир Львович,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
13,acf-008076c876c08dd7c54a05cbec8f82eeaa0af206,Person,semchenkov iurii evgenevich,Семченков Юрий Евгеньевич,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
14,acf-0089427e82e2d014999f7794a7239353425540e2,Person,sagdieva aliya ilsurovna,Сагдиева Алия Ильсуровна,1998-07-04,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
15,acf-009091eb32e7f17dbbb1cd5d4477af24eb168628,Person,gordeev sergey nikolaevich,Гордеев Сергей Николаевич,1968-06-20,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
16,acf-0093a64c6a3abaf4073d9dd3c39bcb37c316e0a0,Person,kutueva gulnaz miratovna,Кутуева Гульназ Миратовна,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
17,acf-00947c4f8b01ec5fbc51eb38f7686fb1400d0614,Person,korobka andrey nikolaevich,Коробка Андрей Николаевич,1982-01-19,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
18,acf-00add013619cb7140b8889410e4a66e1948e8f51,Person,misikov boris ramazanovich,Мисиков Борис Рамазанович,1951-03-25,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
19,acf-00d93131d21cf3cb292cfb370c9402e8f299d64e,Person,mirzayan gevorg valeryevich velerievich,Мирзаян Геворг Валерьевич,1984-01-09,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
20,acf-00e5a2abfd8907fb0c37cbe9334f6c698748103b,Person,gorodilova marina eduardovna,ГОРОДИЛОВА МАРИНА ЭДУАРДОВНА,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
21,acf-00eebe9a0059b398fcdb48e8a65e10392017b3c6,Person,zimenkova faina,Зименкова Фаина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
22,acf-0105c769260d8a74b899b26bc9f4c29a3d415892,Person,kozhevin igor vadimovich,Кожевин Игорь Вадимович,1971-07-26,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
23,acf-0109b3b0ccc72a9cdfb5fe06c247d1f8ba05a840,Person,fesenko inna alexandrovna,Фесенко Инна Александровна,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
24,acf-011870a917f057cc0f2594b6ebcef511db26eb69,Person,nikitchenko vv,Никитченко В. В.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
25,acf-011d788d464aed4450661f9f939260aeec35fa15,Person,kuvaeva oksana vitalyevna,Куваева Оксана Витальевна,1977-02-10,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
26,acf-012a062a7dd54772d4904ce98ffeb99f7be3b3c4,Person,gusev vladimir alexandrovich,Гусев Владимир Александрович,1945-04-25,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
27,acf-012f92b9ff4297c654dea7714fd046c4702e26af,Person,salikhov azamat rafaelevich,Салихов Азамат Рафаэлевич,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
28,acf-013af6ab3d7091149426ee8abc0f46291e6eb2b5,Person,zverev anton vladimirovich,Зверев Антон Владимирович,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
29,acf-01439aadfc543170306978bae3f4ce3b69c14b99,Person,bulatov igor borisovich,Булатов Игорь Борисович,1983-04-04,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
30,acf-0147a160397cc6215275b6c8b6c5fd3ed9a6e994,Person,barinov ilya alexandrovich,Баринов Илья Александрович,1977-10-13,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
31,acf-01523870189e440a38b7923b22c1f630e48497cc,Person,eliseev,Елисеев А. А.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
32,acf-015966ccfea5129961c9a51318efe1e1522546c0,Person,nikolaeva nikolayeva ayna aina,Николаева Айна,1979-12-10,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
33,acf-015f237a0c9cf4374d867e6e4a96ae0ea9c200f8,Person,trusov yuri vasilievich,Трусов Юрий Васильевич,1938-05-25,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
34,acf-015f63c9ad4e1248b296b1ec516c076c2b96abe0,Person,dubrovskaya angelina,Дубровская Ангелина,1989-11-22,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
35,acf-0178bf8014273b868a0e9f20289f9b94a568a10c,Person,davletbakov artur khasanovich,Давлетбаков Артур Хасанович,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
36,acf-018046e37ff211cc56072cdf5a00a127191877e5,Person,khabarov viktor alekseevich,Хабаров Виктор Алексеевич,1967-09-23,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
37,acf-018f89b89155d099a91b32dd896f5a1682ea2973,Person,vasilyeva,Васильева И. М.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
38,acf-01ad27c433600fbdf513e02e4cc428c8a1bd9fce,Person,danilov konstantin ivanovich,Данилов Константин Иванович,1961-05-07,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
39,acf-01baa7db73998c496ce1b827175129e9c909b520,Person,lazarev alexander vladimirovich,Лазарев Александр Владимирович,1974-07-25,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
40,acf-01bf4092585ff006d1656b4ba5d2eec77d7537fc,Person,filippov dmitry igorevich,Филиппов Дмитрий Игоревич,1975-10-28,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
41,acf-01c7aa3e62f5202aa62183c8cbb79a3a4c2b0e2a,Person,sizov sergey nikolaevich,Сизов Сергей Николаевич,1967-06-20,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
42,acf-01df5d6cd919513032563646db0d6bd8df26b3d8,Person,oguryaev dmitry aleksandrovich,Огуряев Дмитрий Александрович,1976-08-25,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
43,acf-01edd9f9f67f7a747fd55b29910fe7c70b7816e1,Person,marchenko,Марченко Т. А.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
44,acf-01eef6556d8ce7ffb078bb292ff3b7546e3e757d,Person,masko alexander vadimovich,Масько Александр Вадимович,1976-08-25,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
45,acf-01f5a6435ce5bfefe507015eaf18fe6a5764b73f,Person,yakubovskaya angela suleymanovna,Якубовская Анжела Сулеймановна,1977,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
46,acf-0211a5a64dcd272c4d5246dff02d086801fa4b47,Person,arshinov alexei alexandrovich,Аршинов Алексей Александрович,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-12 0:49,2023-01-08 12:16
47,acf-0213acd0b66df6b471035ec4e8b4e80ec299ddf9,Person,atuova altynai iunusovna,Атуова Алтынай Юнусовна,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-07-09 18:14,2023-01-08 12:16
48,acf-02429ef9a21e571cb48aa2e7934d37cd549c7451,Person,ismagilov airat talgatovich,Исмагилов Айрат Талгатович,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-05-05 15:26,2023-01-08 12:16
49,acf-026c85a9e6f5f2699991eec4e57eac79766e1e4f,Person,plat pavel vasilievich,Плат Павел Васильевич,1956-02-24,NaN,NaN,NaN,NaN,NaN,NaN,ACF List of bribetakers and warmongers,2022-09-20 1:05,2023-01-08 12:16

# Customer Dictionary

# Matching Name&Birthdate

# Merge Data