In [1]:
import pandas as pd
import glob
import os

In [2]:
from pandas import read_csv

In [3]:
filename = 'match4.csv'

In [4]:
match = read_csv(filename, encoding = "UTF-8")

In [5]:
match

                                             NameBirth matchnum
0                              thomas deadrick19520826       60
1                                   kirk adams19730202       65
2                                dolores kelly19590903       57
3       patricia del carmen de la cruz delucio99999999       86
4            mario arnoldo hernandez colindres19570214       55
...                                                ...      ...
249988                           bauke de haan19390111       67
249989                             anthony ada99999999       86
249990                       bernadette jordan19630407       86
249991                                wes hall19370912       59
249992          daniel augusto melo lima évora99999999       86

[249993 rows x 2 columns]

In [6]:
#read the path
cwd = os.path.abspath('')
#list all the files from the directory
file_list = os.listdir(cwd)
file_list

['.ipynb_checkpoints',
 'match1.csv',
 'match2.csv',
 'match3.csv',
 'match4.csv',
 'match_node.csv',
 'match_node.ipynb',
 'nodes_name.csv',
 'UofT_nodes.csv']

In [7]:
#list all csv files only
csv_files = glob.glob('*.{}'.format('csv'))
csv_files

['match1.csv',
 'match2.csv',
 'match3.csv',
 'match4.csv',
 'match_node.csv',
 'nodes_name.csv',
 'UofT_nodes.csv']

In [8]:
match_all = pd.DataFrame()
#append all files together
for file in csv_files:
            df_temp = pd.read_csv(file)
            match_all = match_all.append(df_temp, ignore_index=True)
match_all

D:\Anaconda3\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

,67,BIRTH_DT,CASH_CNT_IN,CASH_CNT_OUT,CASH_SUM_IN,CASH_SUM_OUT,CNTRY_OF_INCOME_CA,COUNTRY_RISK_INCOME,COUNTRY_RISK_RESIDENCY,CUSTOMER_ID,...,OCPTN_NM,PEP_FL,RES_CNTRY_CA,RISK,WIRES_CNT_IN,WIRES_CNT_OUT,WIRES_SUM_IN,WIRES_SUM_OUT,matchnum,matchnumchris phillips19691008
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999946,NaN,1939-01-16,10.0,21.0,18945.108,32210.000,1.0,Low,High,420884.0,...,467.0,0.0,0.0,high,25.0,174.0,1186467.0,2550098.0,NaN,NaN
2999947,NaN,1970-12-13,7.0,15.0,5775.601,5015.741,1.0,Low,Low,429418.0,...,467.0,0.0,0.0,low,53.0,337.0,244504.0,417992.0,NaN,NaN
2999948,NaN,1958-09-09,2.0,19.0,2351.255,15997.000,1.0,Low,High,731360.0,...,65.0,0.0,0.0,high,68.0,124.0,3024271.0,948981.0,NaN,NaN
2999949,NaN,1983-09-15,8.0,5.0,27312.613,3399.000,1.0,Low,High,837988.0,...,231.0,0.0,0.0,high,9.0,12.0,943477.0,376429.0,NaN,NaN
2999950,NaN,1962-01-23,1.0,1.0,1421.363,1276.000,0.0,High,High,166357.0,...,89.0,0.0,0.0,high,5.0,12.0,683797.0,617628.0,NaN,NaN

# Merged_match data

In [9]:
# Only keep NameBirth and matchnum column in the dataframe
match_all = match_all.loc[:, ('NameBirth', 'matchnum')]
match_all

                                       NameBirth matchnum
0                         young han park99999999       86
1        marcus elliott aka mark bentley19900909       86
2                          dean garforth99999999       86
3                            helge lindh19761206       62
4                         carolyn thomas19650000       86
...                                          ...      ...
2999946                                      NaN      NaN
2999947                                      NaN      NaN
2999948                                      NaN      NaN
2999949                                      NaN      NaN
2999950                                      NaN      NaN

[2999951 rows x 2 columns]

In [10]:
full_list = match_all[match_all['NameBirth'] != 'nanu cornel99999999']
full_list.count()

NameBirth    1998631
matchnum      749463
dtype: int64

In [11]:
# sort by matchnum
actor_list = full_list.to_numpy()
actor_list90_name = []
actor_list90_val = []
for val in actor_list:
    name = val[0]
    match_num = val[1]
    
    if(not isinstance(match_num, str) and match_num > 86):
        actor_list90_name.append(name)
        actor_list90_val.append(match_num)
actor_list90_val

[87,
 88,
 90,
 89,
 89,
 89,
 89,
 87,
 88,
 89,
 89,
 87,
 91,
 87,
 90,
 95,
 87,
 89,
 89,
 88,
 89,
 89,
 90,
 89,
 87,
 89,
 88,
 89,
 92,
 88,
 87,
 90,
 91,
 88,
 90,
 91,
 88,
 87,
 89,
 95,
 88,
 88,
 88,
 91,
 88,
 88,
 88,
 88,
 90,
 87,
 90,
 87,
 90,
 87,
 88,
 91,
 88,
 89,
 89,
 87,
 88,
 88,
 91,
 88,
 89]

In [12]:
# read node.csv
nodes = read_csv('UofT_nodes.csv', encoding = "UTF-8")

In [13]:
# extract NameBirth from node.csv, generate a list of string
import csv
node_name_arr = []
with open("nodes_name.csv", newline='', encoding='UTF-8') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        node_name_arr.append(row['NameBirth'])
node_name_arr

['young marie mildren coleman19810901',
 'mark stupar lecy19940221',
 'dean glasper wendel reeves19621116',
 'hulsey linda rauth19980620',
 'carolyn washington roberts19420124',
 'mary gilmore an19690522',
 'jacqueline thompson burke spann19510331',
 'alderson james mccombs wilcox19860826',
 'morris maria bitto minnick20020624',
 'mcneil jennifer delargy park19680113',
 'page sharon peak buroker19571111',
 'suzie garcia lavelle20070626',
 'sanders ronald schwerdtfeger19681011',
 'jeanette williams krishun19781220',
 'phipps mary sanchez smith19810305',
 'danny aso tindle19790618',
 'randy hunter summer19770327',
 'michelle pederson carlson mcilhinney19500716',
 'opal mapp diamond miller19560706',
 'reed victoria dreessen lamontagne19891021',
 'jackson birdie calkins19840820',
 'klug denice19940116',
 'nelson jason niceswander19511010',
 'rowena jennings ervin19900516',
 'patricia wallner werner mcclain19450221',
 'romero david19450930',
 'kinser rose hill taylor19550915',
 'cheryl phares simpson carranza20030123',
 'susan gordon19520713',
 'julie smith owen smith19690809',
 'wilson sally19880901',
 'vasquez marian pacheco fawver19261115',
 'irene stone king diaz19581115',
 'betty pener aen19770927',
 'wixston ashley manes19661129',
 'frances gould19840512',
 'jimmy mierzejewski perez19470905',
 'katherine white her forsmark19660307',
 'charles boucher barrera19570326',
 'schade brian williams19500709',
 'english joan glosson19660909',
 'joseph millett strawn culp19570107',
 'juan lund kim miller19580821',
 'robert smith mchugh19801006',
 'sharon long navarro19661126',
 'james warren whitehead19950728',
 'hopper corey roberts wallen19791004',
 'miller mary20090109',
 'hancock cindy hairston elliston19921128',
 'iris johns joe bischoff19670304',
 'olivia dennis19970209',
 'ricky willis hiers19950610',
 'mcclure jennifer powers19750510',
 'preston grant williams pioske19590101',
 'loreztta mccardell medina19681121',
 'kennedy katie vaughn moya19500619',
 'wendy bowman aveline phillips19840828',
 'harkins lesley fernandez gillespie19950522',
 'adriana overstremet flinn19751121',
 'harper anna mahan hutcherson19531229',
 'brian galyean woods secrease19511012',
 'higa michael rivers mittman19731020',
 'june case scott19701105',
 'alexander jam cusumano19500603',
 'witherspoon odessa street19920219',
 'morales tammy jones mckeever19721028',
 'clifford morgan perie abramson19971206',
 'nathan heald abbott19660624',
 'chauez robin19930302',
 'mary roy cheatom19780226',
 'tracy caldwell andrews19471003',
 'william wolfe reynolds rice19510406',
 'carey sibley good lee19670220',
 'jan moore elizondo19611026',
 'ahlsi white19641124',
 'collins donald cordial irving19860213',
 'ilon jessie weidman bedford19401025',
 'luz moss19670324',
 'michelle desoto pope lopez19510615',
 'mary ferber smith richardson20111001',
 'quesada carlos19731219',
 'holland cleopatra peno19600718',
 'widell vivian ahn19790704',
 'belinda shaw beasley19941012',
 'sharon gurley gauthier19910226',
 'jack denham scott20061021',
 'edith randall khan schumpert19960509',
 'johnson howard bogdon19551015',
 'kelly schmid mcneil19800924',
 'craig plourde gietz clattenburg19750413',
 'randy wooley keller19800811',
 'ruth wetherington19820104',
 'paniagua john zaleski19720916',
 'dustin clark houston mui19980320',
 'bulson regina whitehead powell19600207',
 'andy kinnan little19650923',
 'mary main knight garcia19410918',
 'harris donnie mcpeattehr19511005',
 'mangan laura nowlin day20030820',
 'jon bradley baber19950517',
 'gretchen lovitz robinson19970819',
 'juana rudder fernandez gumm19841205',
 'jason youns monarrez19620116',
 'georgia gunther19930410',
 'gordon iris johnson mcclish19980214',
 'lawrence council taylor20070808',
 'hernandez denise murphy bennett19640804',
 'smith ona jones geiger19650802',
 'vanderploeg reina ocegueda19951025',
 'vicki meir scott tran19771221',
 'burns linda buford roth19551001',
 'joel finch clark19860702',
 'angel smothers19870211',
 'larry schad schumacher hart19700325',
 'lane michael reyna19770416',
 'glenda tucker king19470308',
 'pelletier dralene martin henderson19571009',
 'wayne battle hunter19600326',
 'doris michaud vela19780624',
 'emily harris hillman19520414',
 'beale helen lane19550621',
 'russell jenkins19530705',
 'matthew yarbrough pratt20000528',
 'nicole mcclain dawson19390731',
 'mcclure richard evans fennell20100615',
 'keith hernandez plummer19670929',
 'kristen henderson morgan19560720',
 'tribble stacy blee rodriguez19550329',
 'richardson jenny denson obrien19640217',
 'little lindy beatty ramirez19720318',
 'edna clark delamora giorgio19890824',
 'kevin layton schneider scott19530313',
 'brian mullins maglio brown19580726',
 'morin gloria rogers murphy19890121',
 'antonio rawlins nolan20090306',
 'ann albano smith burlew19330324',
 'beebe timothy omp kennedy19720411',
 'greg rust brixey19711116',
 'valentine matthew nichol crittle19570810',
 'theodore phillips rodriguez19841221',
 'jerry soto corell19960501',
 'kaiser theresa latham castro19600603',
 'dennis williford benson smith19850809',
 'norma bruster white19791107',
 'eva scarce19770906',
 'lewis morales barksdale19580303',
 'daniel anderson wilson19590716',
 'jennifer williams19920915',
 'dorothy giannecchini lawrence goodale19700111',
 'davidson roy woods19650616',
 'kevin mcclure havenhill mckinnon19920814',
 'robinson nadia theis gwin19680217',
 'collins rosemary colella19720912',
 'joseph morse partridge19800317',
 'emma giliberto marcos19310107',
 'gerald ruff gambill jefferson19450730',
 'dyer wesley19721125',
 'david herb morgan19930630',
 'betty steadman schwartz mcguffee19720424',
 'mccartney schuetz19840918',
 'gary harvey spatz19910214',
 'janet lorna gillikin rowley19851230',
 'joel meyer whitehead19780124',
 'rundell lawrence clark20040917',
 'lori barke hall19880116',
 'daniel ford19570306',
 'juan beringer woodson19660917',
 'benson marvin mcdonald19960317',
 'gerrior patricia19451007',
 'tunnell victor bernabe edwards19880728',
 'amy murray simm19460331',
 'johnnie albritton cunningham19390907',
 'dennie audra parker19851203',
 'lopez michaela19831015',
 'solano jason tillman williams20121012',
 'keith dennis19690703',
 'edward furstenberg call toscano20060314',
 'dance hal niskanen20030616',
 'meyer marie barnes19771224',
 'brenda king19701106',
 'gene pierce kahl19840403',
 'carla gunter geisler anderson19730706',
 'rule andrew flynn webber19460406',
 'evers rita maas smith19720215',
 'bailey chad19571003',
 'tina goodwin20041002',
 'gilberte gustafson19730127',
 'erro jordan singleton wright19590120',
 'steib marian cooper19440604',
 'betty darrow corona19920503',
 'alvaro bostwick19460105',
 'fullerton mary pisano19790331',
 'lainie anderson lafleur19980511',
 'natalie holstein graham19580513',
 'bill nelson wolff putnam19720730',
 'joan southwood barnett19480603',
 'labadie burl hotchkiss19910223',
 'burnett anthony gu old spence19681009',
 'mary roser johnson filmore19590323',
 'james lahr toti cote19490731',
 'elsa jean mccrary wells19690408',
 'stephen osborne dorst19780526',
 'cathy hungerford19640527',
 'donald stai dennis19890708',
 'nathan zeff salyer19720116',
 'joan deming garza19610614',
 'zorn amanda partis mccollum19951008',
 'moses deforest19790412',
 'rea mcgill reik19920605',
 'arthur nobles thompson19780720',
 'weaver dennis peters19720510',
 'antone fernandez nall19421014',
 'beverly mitchell batton19610512',
 'jason field south19741101',
 'lois maguire cotton brown19820603',
 'ayala janet arellano19720409',
 'julieta beaudin ryland yarber19471115',
 'huff earl tmi clifton19560709',
 'martha grosser hernandez19980404',
 'eunice white ellis renner19801021',
 'perrotti donald perrington garske19480827',
 'mcintyre dorothy morales martinez19670830',
 'lori pruitt sawyers19670711',
 'roller mary wright zink19790315',
 'tisdale monica ortiz pullen20170614',
 'terry hollingshead buchanan20000907',
 'pamela wisnowski sower19381022',
 'mabel alfonso sanders19640707',
 'maurita talbert barginear allen19900323',
 'angela green19890317',
 'cynthia cloninger sanders thompson19720209',
 'kennedy sherry murray20011007',
 'caroline bunnell coleman19900127',
 'port iarvmn hale20030130',
 'perez yer younglas poon19620527',
 'elease melton ga anderson19740928',
 'mitchell edward voris wilson19900902',
 'bernard garcia turner greenfield19610228',
 'hazel marsh19921015',
 'lyman ellwanger yochum19500408',
 'edwin ryder19900612',
 'carlton barron jageman jude20050607',
 'schug jack mcewen19670917',
 'robert ba calvillo19541012',
 'ball dawn villanueva19561121',
 'harry gerry durham19950417',
 'shirley stokes vandyke sincell19890701',
 'mccray patricia beehler dotson19570509',
 'roye stephanie lawson lathrop19710720',
 'floyd ledford mills lloyd19760530',
 'emerson wilbur scudder craddock20171007',
 'fred lough19740625',
 'oxford richard meadows19981223',
 'miriam ddu doherty19830915',
 'dolly newcomer tucker19461020',
 'antonio flowers westbrook hawthorne19990507',
 'jeff jessie kreider19840924',
 'burks elizabeth strawn caughlin19890826',
 'jennifer gilfillan miller thao19670910',
 'maryann peterson lyons19631209',
 'elen rae shapiro martin19800304',
 'jeffrey strickland snyder hill19500605',
 'jessie walsh lerma stoll19910826',
 'welch james johnson couch19990104',
 'daniels rosemary tucker19800209',
 'peter davidson manciel19450828',
 'colin plowman griego johnson19740606',
 'terrell crafton19301211',
 'irene love marmerchant hunter19650227',
 'jason oliveri selkirk19700728',
 'dora carr19790815',
 'bloom tracy joffrion19860725',
 'gertrude naeg fuller19730517',
 'theresa wheat hagen19691213',
 'ressie sewell19890827',
 'kathryn stuart gaines cooper19680318',
 'hargrave bruce cardenas19651011',
 'david ogaldez sayed19960116',
 'david anderson wooden crewe19760910',
 'alicia rice20080811',
 'florence randolph20030121',
 'barbara mais pacheco lairy19470126',
 'rosario pamela marsh aronson19841006',
 'kristin seale klein19960107',
 'phillap kin nava kocher19860619',
 'bardley morren parra reina19700205',
 'nanc19811205',
 'conrad keegan stull gray19631221',
 'pender waneta mccoy edgecomb19660227',
 'deborah gulley davis19410517',
 'thompson richard hernandez19590927',
 'debra singley harrison19360505',
 'jay polson henschel19810820',
 'barnes wendy19940530',
 'margaret citron foody19870224',
 'william nadeau guzman19670515',
 'marquis vicky george sanders19791118',
 'louis pierson lawson19540325',
 'johnny bartholomew miller19850822',
 'crawford andrew lockett lewis19680928',
 'sally gray martin19960621',
 'pearlie davis19360715',
 'catherine anderson taylor bromley19920423',
 'moye anerda earles bombich19790401',
 'clark williams winters19831215',
 'jill tucker19580513',
 'wise flora addie lantz19551128',
 'ison aaron atkison19731220',
 'martha jackson avila19781019',
 'pearman chl long19780819',
 'kay murrell wells19550821',
 'ramirez shirley lopez daugherty19980405',
 'mary hughes jackson gonzales19690701',
 'laura hill bennett19620708',
 'yolanda smith dossett corder19681111',
 'brian graham mercer19411125',
 'julie keeler ortiz19620927',
 'louise yerian keithly19620610',
 'kristi smith19840129',
 'sims christopher mcdaniel wolfrum19990126',
 'richard moore19650109',
 'colette zabel jaeger19340223',
 'bobby snook sccauley19560914',
 'kintner robert slone19870611',
 'corbin niunete minichiello19760106',
 'alice mckay thomas19930627',
 'mathis karen gantt gose19820204',
 'carter barbara sampieri20000215',
 'rumsey rosa morlino thompson19650105',
 'royce susan beebe boswell20161103',
 'kenneth nickson diaz lilley19860111',
 'che ster watson mcqueen rose19841016',
 'ed jones messersmith moultrie19971017',
 'daniels marcie wright19830101',
 'tina thomas metzner graves19690416',
 'brashear shannon corder eld19771115',
 'hampton barbara ynuoger19660329',
 'alan kruse peterson19901019',
 'sheila owen gillette19910821',
 'katie hinh fitzpatrick19990729',
 'hembree joseph smith rivera19570807',
 'florence sims gonzalez thompson19411201',
 'paul mawyer haddox20031130',
 'gauthier janice richard boone19520104',
 'james alamo19840315',
 'mary villalobos davis19790702',
 'ruiz robert worton19820409',
 'eda edna zachmann19830329',
 'deborah rosales mooney19700717',
 'robert bellinger maldonado mason19890921',
 'dorothy taylor wright19760403',
 'ramon chan gilbert19871219',
 'pham benjamin thompson gonsalves19591203',
 'curtis porter19730217',
 'penelope singleton19740414',
 'cofer gary19730517',
 'jason davis lester lawrence19740121',
 'egger abraham lentz purdy19940109',
 'irma aguirre hart eiw19710201',
 'jeffery merk holcombe19760407',
 'moldenhauer nat mesias mason19750823',
 'richard aaron19820407',
 'lauren hooten19930515',
 'amber sanford turner stewart19800229',
 'maxine palmer cochran mackenzie19561101',
 'calvin parker francis rahmani19550613',
 'clever daniel ott taft19430415',
 'david jones rittenhouse robbins19991123',
 'gordon isadora pierce19511018',
 'jacobs mervin lu19660318',
 'evangelina veil stanley munoz19590118',
 'pamela grieco charlesworth hadlock19710327',
 'jose hagen kennedy19860804',
 'bonita rice crosby jenner19790305',
 'billings rachel keats19990614',
 'wicks sanford pettit shelley19980701',
 'sidney tolbert hernandez drewett19720731',
 'bennett mindy reisman19650606',
 'rena armstrong key19720211',
 'felicia walker loveall avery19780806',
 'katie smith king leambrecht19630214',
 'osborn richard poling diehl19700326',
 'solesbee samantha oliva tilley19630426',
 'watts bart19880913',
 'rush isaac osborn19780818',
 'brian nicholas johns19950322',
 'david previte20020301',
 'jenifer rickman burgess19810715',
 'amie brown vanhorn19550327',
 'green jhjn larson19850216',
 'mccrary shannon hunt19351204',
 'benny bailey messenger19821119',
 'rachael dana bryant sorensen19821111',
 'alexander fair russell19750802',
 'kevin wilson mullins holliday19750331',
 'nancy lawler robinson davila19520820',
 'adam applin mallet foster19620702',
 'gabrielle spitzer19810611',
 'hoover sadie philbert19621024',
 'betty ott brigman19390119',
 'leah farmer webb hawkins19540919',
 'florine jordan19680116',
 'wynne brenda degraff quinn19981228',
 'bessie williams crockett19750415',
 'burke betsy mulac harvey19550313',
 'lisa jackson friend hirsch19710528',
 'mcfadden nanny staschke tower19640324',
 'brian matava young19780927',
 'pierce jesus ruff19730131',
 'el hefner walker romero19680730',
 'gregory siewert lewis savage19670816',
 'anna caudle durand poehlman20110319',
 'paul sheehan cole19890213',
 'barksdale bryon esbenshade19760103',
 'rosetta hershberger belser19700927',
 'eick riggs20120314',
 'calvin mumford monroe mccormick19680326',
 'jimenez angelo bane20070315',
 'flores brigitte19751130',
 'jeffxey wright henry19920213',
 'deeter david jones19850607',
 'doris vanderhorst jackson pollock19800705',
 'mary iddings benitez scholler19780625',
 'daniel holland tsuda percy19930514',
 'teresa parrish krok hayes19590812',
 'valdez amanda19760510',
 'cathy self kent19970508',
 'bonnie bell mitchell19981011',
 'michael petrey20060630',
 'breiner thomas constance19770323',
 'fox scott ratliff19940531',
 'ryan gloeckner20020204',
 'molly bogucki russell20101129',
 'rodriquexz vince sheridan smith19810309',
 'trease genevieve19800724',
 'sherrie richardson jones mackay19950601',
 'sherri grayson price19860628',
 'on cumings montoya pierce19990628',
 'annie brooks zwick martin19710621',
 'martin carla trimpe salamanca19800916',
 'steven reeves mittltseadt19620325',
 'kelli hanks kostrzewa teague20121113',
 'lisa avila crabill19620531',
 'irene willett mccaskin19661124',
 'georgie quiroz19731203',
 'ralph mendibles campbell19320818',
 'george doyle judge19761028',
 'thomas barton wise19920713',
 'sadie clements ellis19771126',
 'tina weeks custodio19651220',
 'winkleman raymond hussain orf19611016',
 'stuart davis gilbert19630113',
 'peter bennett pinto19710605',
 'phyllis glasser cromwell19701215',
 'holmes jamie gallegos19610701',
 'gutierrez john dell19670729',
 'smith mathew bray leitner19920405',
 'kathryn hogan19740427',
 'jonny mcginty saiz19980330',
 'justina minardi jones hill20100330',
 'susan bussen larson19730829',
 'rose brandt20110729',
 'ward sofia dumont miyamoto19680525',
 'george ferdinand sharp19811229',
 'susana longerbeam simmons19910719',
 'doug dever holloway green19931007',
 'shelly moore20040926',
 'ralph monnier reese brewington19920512',
 'smith june gaut lamb19790109',
 'gerald flagg martino19691112',
 'manuel ramirez wright martinez19720803',
 'ruth white freeman lautenschlage19870117',
 'pamela mosley gilson nlla19330725',
 'moreland nora buchholz19690526',
 'figley nlcoie thompson early19580113',
 'smith leslie douglass bussey19760814',
 'oscar moses runyan19530929',
 'chelsea keller veenstra moore19911013',
 'genoveva gregg greenwood lounsbury20111013',
 'andrews roger atkins19810420',
 'lawrence kawai carr fortenberry19530515',
 'hendrix rosa wheeler19650115',
 'pamela eastridge hawes wonders19771113',
 'maria riahcrdson stanley perez19870415',
 'racheal fluellen evans19520727',
 'robert earle laing ames20080327',
 'amy meza harloff payne19780810',
 'dianne allen19550216',
 'carrie berwick robinson aran19631106',
 'jimmy holmgren alvarez ba19631201',
 'nancy smith scott linder19560604',
 'walter kimberlin keller seward19751020',
 'scott mull archer barksdale19830803',
 'maria chadwick foster19930116',
 'carzolyn ramirez chrlton burney19780316',
 'laura ransler sexton19921207',
 'gonzalez virginia hare carter19380425',
 'brown rebecac19820919',
 'jeffrey legrand oglesbee meek19360903',
 'eve gonzales cahee wilson19881212',
 'judith ross hood19421204',
 'diane thruman arbou19970228',
 'wright eleanora murphy19540311',
 'russell kearney pope19490429',
 'agnes vazquez19940816',
 'ray parks smith19431002',
 'norman fowler riggie esarza19801121',
 'michael mecham howse adams20031110',
 'jagger jimmy fowler hcale19811030',
 'bennington carlos go hopper19801023',
 'charles ella quinn19470718',
 'kennedy william lyell pouth19750610',
 'michael fletcher waterman holden19750117',
 'vandestreek ronnie davidson mith19860913',
 'lak wanda20020105',
 'clarence goode outlaw myles19780810',
 'catherine robbins baker turner20080609',
 'chapman betty williams donaldson19781020',
 'rebecac boyce cataline19950708',
 'collier david unnasch19750505',
 'portes linda dunham manns19730615',
 'irittabn jeff warthen stringfellow19631003',
 'cox mary gray19780802',
 'johnson marion krause ebling19760421',
 'guy paul wilson19780119',
 'jacqueline wright maurer19650518',
 'charles sermersheim gholston runyon19631102',
 'rocio buck perdue arroyo19880624',
 'don warren peoples blackwell19620320',
 'lloyd janick martinez19850607',
 'elaine alger raio19700416',
 'alma phillips rooker19740528',
 'john busch washburn patenaude19980219',
 'nguyen chebryl melton19480503',
 'jonny rounds19871110',
 'grover emos parmer forbes19761218',
 'elizabeth kim jones may19651121',
 'kelly oconor yip devereux19920104',
 'raymond leyva mathews mckeeman19780514',
 'savic jennifer deeds bonham19801228',
 'koller alan hutson hendrickson19481106',
 'bell robert dasilva gephart19660321',
 'michael brown johnson em erson19770222',
 'patricia derosier worth19701002',
 'capaldi rosemary dickson19960929',
 'joan wright zimmerebner19780404',
 'john miramontes hunt19701212',
 'cochran eddie koch19930805',
 'veronica spencer cooper rusin19650609',
 'ruben collins blunt abel19750605',
 'joseph zinn holliday19850717',
 'win evans perea hrtl19480326',
 'charlotte kuehn wright19410625',
 'courtney wilson sarette howarth19721031',
 'jimmie sanderlin zapata20121121',
 'norris evelyn gant edwards19521218',
 'wert leola thompson nolan20000101',
 'gregory hogsett cary19560209',
 'allen bonita gordon19690404',
 'hudson rita hagan pearson19690123',
 'judith conn park19701119',
 'matthew measheaw beltrami fournier19940322',
 'alice mendez downes19460518',
 'ashley20160222',

In [14]:
# Create a csv file to save output
header = ['NameBirth', 'matchnum']

with open('match_node.csv', 'a') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [15]:
from fuzzywuzzy import process

for i in range (len(actor_list90_name)):
    extracted_name = actor_list90_name[i]
    print(extracted_name)
    val = process.extractOne(extracted_name, node_name_arr)
    name = val[0]
    match_num = val[1]
    print(name,match_num)
    with open('match_node.csv', 'a', newline='', encoding='UTF-8') as f:
        writer = csv.DictWriter(f, fieldnames=header)
        writer.writerow({'NameBirth': name, 'matchnum': match_num})

david alexander19521029
david alexander19751016 87
richard thompson19470000
richard thompson19771009 88
john flowers19540114
john flowers19441214 90
christina henderson19851010
christina henderson19641020 89
eric smith19420911
eric smith19720611 89
john young19301221
john young19830321 89
david ward19530429
david ward19630426 89
michael johnson19700131
michael johnson19771230 87
steve martin19601003
steven martin19550103 88
robert king19461227
robert king19691226 89
susan combs19450201
susan combs19650320 89
michael praßl19550915
michael pal19650911 87
jerry williams19410215
jerry williams19581025 91
richard nichols19260429
richard nichols19820125 87
james martin19351211
james martin19510521 90
thomas obrien19640315
thomas obrien19640531 95
frank grass19510519
frank grasso19510621 87
john barnes19310821
john barnes19930811 89
david davis19591106
david davis19501016 89
suzanne williams19450203
suzanne williams19701013 88
andy davis19750528
andy davis19750412 89
david myers19611231
david myers19461124 89
daniel allen19890328
daniel allen19850324 90
keith bell19620622
keith bell19620306 89
rebecca harris19671222
rebecca harrison19671216 87
david clark19530703
david clark19520803 89
christopher smith19530304
christopher smith19540424 88
earl jones19490720
earl jones19901208 89
david duguid19701008
david guidi19701008 92
christopher gibson19530705
christopher gibson19800524 88
marlene johnson19460111
marlene johnson19600915 87
cheryl brown19440211
cheryl brown19450311 90
sarah campbell19820719
sarah campbell19871009 91
marty williams19510305
mary williams19550310 88
john edwards19431006
john edwards19391001 90
andrew johnson19530112
andrew johnson19320911 91
peter reekmans19750109
peter freeman19750610 88
lyn allison19461021
lynn allison19841210 87
james thomas bailey19750201
james thomas bailey19450731 89
robert obrien19660618
robert obrien19660611 95
christopher miller19651015
christopher miller19631006 88
andrea schroeder19640602
andrea schroeder19500927 88
robert rodriguez19760411
robert rodriguez19600218 88
william daniel19551106
william daniel19550623 91
michael harrison19580909
michael harrison19800405 88
jim ott19470605
jim scott19470805 88
kathleen williams19610216
kathleen willis19640616 88
brian montgomery19560802
brian montgomery19350329 88
david thomas19581220
david thomas19520208 90
michael spencer19550530
michael spencer19850425 87
robert garcia19550504
robert garcia19650604 90
thomas reynolds19500903
thomas reynolds19690303 87
ronald miller19541112
ronald miller19521116 90
james kelly19631023
james kelley19321213 87
lee perry19660810
lee terry19660106 88
bruce thompson19531124
bruce thompson19541128 91
bryan taylor19760302
brian taylolr19760630 88
andrew moran19620509
andrew ira19620509 89
john wright19540805
john wright19460505 89
david christopherson19541005
david christopherso19560528 87
michael williams19291016
michael williams19910709 88
christopher murphy19730803
christopher murphy19630304 88
kathy campbell19461201
kathy campbell19941010 91
richard wills19450618
richard willis19590608 88
brian moore19620102
brian moore19680127 89